export const USER_SERVICE_PROVIDER_KEY = 'USER_SERVICE_PROVIDER_KEY';
export const APP_SERVICE_PROVIDER_KEY = 'APP_SERVICE_PROVIDER_KEY';
export const STORE_SERVICE = 'STORE_SERVICE';

export const APP_FB = 'APP_FB';
